import type { Field } from './types';

export const CROP_OPTIONS = ['Corn', 'Soybeans', 'Wheat', 'Alfalfa', 'Oats'];

export const SEED_FIELDS: Field[] = [
  {
    id: 1,
    name: 'North 40',
    crop: 'Corn',
    acres: 38,
    status: 'rotate',
    risk: 78,
    reason: 'Nitrogen has dropped 30% over 2 years of corn; predicted yield down 18% if repeated.',
    confidence: 'High',
    lastScan: '2 days ago',
    suggestedCrops: ['Soybeans', 'Winter Wheat', 'Alfalfa'],
    durationLabel: 'Decision window',
    durationRange: 'Now — plant within 2 weeks',
  },
  {
    id: 2,
    name: 'Creek Bottom',
    crop: 'Soybeans',
    acres: 52,
    status: 'safe',
    risk: 22,
    reason: 'Soil nitrogen is stable and no pest-cycle risk was detected for a repeat planting.',
    confidence: 'High',
    lastScan: '5 days ago',
    suggestedCrops: [],
    durationLabel: 'Next rotation decision',
    durationRange: 'Sep 15 – Oct 1',
  },
  {
    id: 3,
    name: 'East Ridge',
    crop: 'Corn',
    acres: 64,
    status: 'marginal',
    risk: 52,
    reason: 'Organic matter is trending down; yield impact is moderate but manageable this season.',
    confidence: 'Medium',
    lastScan: '1 day ago',
    suggestedCrops: ['Soybeans', 'Oats'],
    durationLabel: 'Next rotation decision',
    durationRange: 'Aug 20 – Sep 5',
  },
  {
    id: 4,
    name: 'South Flat',
    crop: 'Wheat',
    acres: 29,
    status: 'safe',
    risk: 15,
    reason: 'Strong soil recovery after wheat; repeat planting is favorable this cycle.',
    confidence: 'High',
    lastScan: '3 days ago',
    suggestedCrops: [],
    durationLabel: 'Next rotation decision',
    durationRange: 'Jul 30 – Aug 10',
  },
];
